### ISSUE TITLE
[Bug]: game crashes when you switch to survival, even with the new discord patch installed

### ISSUE THREAD

**Issue by blockEdragon** [DragonSurvivalTeam/DragonSurvival#128]
### ■ Your Discord ID

blockEdragon#5057

### ■ Dragon Survival version

DragonSurvival_DragonEditor -1.16.5-0.13.42_nonpublic_fix

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

The game crashes when in survival mode as a dragon.

### ■ To Reproduce

1. Start in creative, place your altar block and use it to select dragon, switch to survival mode, the game will crash.
OR
2. start in creative, place altar block, switch to survival mode, select a dragon, the game will then crash

I have not tested getting the block by staying in survival and crafting it.

### ■ Expected behavior

I expect the game to run properly as a dragon in survival mode.

### ■ Crash Report

---- Minecraft Crash Report ----
// My bad.

Time: 3/28/22 12:37 PM
Description: Ticking player

java.lang.ArrayIndexOutOfBoundsException: 2
	at by.dragonsurvivalteam.dragonsurvival.config.ConfigUtils.parseConfigItemList(ConfigUtils.java:28) ~[?:1.16.5-0.13.42] {re:mixin,re:classloading}
	at net.minecraft.item.Item.md59e9fd$lambda$onItemUpdate$0$2(Item.java:1036) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:APP:dragonsurvival.mixins.json:MixinItem,pl:mixin:A}
	at net.minecraft.item.Item$$Lambda$15482/2014478298.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.item.Item.handler$zii000$onItemUpdate(Item.java:1035) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:APP:dragonsurvival.mixins.json:MixinItem,pl:mixin:A}
	at net.minecraft.item.Item.func_77663_a(Item.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:APP:dragonsurvival.mixins.json:MixinItem,pl:mixin:A}
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:434) ~[?:?] {re:mixin,re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:238) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:MixinPlayerInventory,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:487) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:APP:dragonsurvival.mixins.json:MixinPlayerEntity,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tenshilib.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:environmental.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:werewolves.mixins.json:LivingEntityInvoker,pl:mixin:APP:improvedmobs.mixins.json:GuardianMixin,pl:mixin:APP:dragonsurvival.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:APP:dragonsurvival.mixins.json:MixinPlayerEntity,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:betterendforge.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$13584/669943504.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at by.dragonsurvivalteam.dragonsurvival.config.ConfigUtils.parseConfigItemList(ConfigUtils.java:28) ~[?:1.16.5-0.13.42] {re:mixin,re:classloading}
	at net.minecraft.item.Item.md59e9fd$lambda$onItemUpdate$0$2(Item.java:1036) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:APP:dragonsurvival.mixins.json:MixinItem,pl:mixin:A}
	at net.minecraft.item.Item$$Lambda$15482/2014478298.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.item.Item.handler$zii000$onItemUpdate(Item.java:1035) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:APP:dragonsurvival.mixins.json:MixinItem,pl:mixin:A}
	at net.minecraft.item.Item.func_77663_a(Item.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:APP:dragonsurvival.mixins.json:MixinItem,pl:mixin:A}
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:434) ~[?:?] {re:mixin,re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:238) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:MixinPlayerInventory,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:487) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:APP:dragonsurvival.mixins.json:MixinPlayerEntity,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tenshilib.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:environmental.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:werewolves.mixins.json:LivingEntityInvoker,pl:mixin:APP:improvedmobs.mixins.json:GuardianMixin,pl:mixin:APP:dragonsurvival.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:APP:dragonsurvival.mixins.json:MixinPlayerEntity,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 253
	Entity Name: blockEdragonn
	Entity's Exact location: 252.50, 65.00, 113.50
	Entity's Block location: World: (252,65,113), Chunk: (at 12,4,1 in 15,7; contains blocks 240,0,112 to 255,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.03, -0.08, 0.07
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:betterendforge.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$13584/669943504.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1831407584 bytes (1746 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.2
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TenshiLib-1.16.3-1.3.0.jar                        |TenshiLib                     |tenshilib                     |1.16.3-1.3.0        |DONE      |Manifest: NOSIGNATURE
		TreeChop-1.16.4-0.14.0.jar                        |HT's TreeChop                 |treechop                      |0.14.0              |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.16.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.16              |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.465-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.463   |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.6.4.90.jar                           |Just Enough Items             |jei                           |7.6.4.90            |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		MedievalCraft-1.16.5-1.16.2.jar                   |Medieval craft                |medieval_craft                |1.14.4              |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |DONE      |Manifest: NOSIGNATURE
		Goblins_Dungeons_1.0.4.jar                        |Goblins & Dungeons            |goblinsanddungeons            |1.0.4               |DONE      |Manifest: NOSIGNATURE
		whisperwoods-1.16.5-2.0.2.jar                     |Whisperwoods                  |whisperwoods                  |2.0.2               |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.16.4-2.2.1.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.1               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.2beta7.jar                  |Journeymap                    |journeymap                    |5.7.2beta7          |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |DONE      |Manifest: NOSIGNATURE
		OuterEnd-0.2.14.jar                               |The Outer End                 |outer_end                     |0.2.9               |DONE      |Manifest: NOSIGNATURE
		fantasy-forge-1.1.1.jar                           |Fantasy Mounts                |fantasy                       |1.0                 |DONE      |Manifest: NOSIGNATURE
		environmental-1.16.5-1.1.0.jar                    |Environmental                 |environmental                 |1.1.0               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |DONE      |Manifest: NOSIGNATURE
		BadMobs-1.16.5-9.0.3.jar                          |BadMobs                       |badmobs                       |9.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.16.5.1.2.4.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |DONE      |Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.8.3.jar                        |Vampirism                     |vampirism                     |1.8.3               |DONE      |Manifest: NOSIGNATURE
		Werewolves-1.16.5-1.8-0.5.6.jar                   |Werewolves                    |werewolves                    |0.5.6-alpha+20210922|DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
		smallships-1.16.5-1.8.5.jar                       |Small Ships Mod               |smallships                    |1.8.5               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-universal.jar                 |Forge                         |forge                         |36.2.2              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-314.jar                                |Quark                         |quark                         |r2.4-314            |DONE      |Manifest: NOSIGNATURE
		improvedmobs-1.16.5-1.8.jar                       |Improved Mobs Mod             |improvedmobs                  |1.16.5-1.8          |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v4a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v4a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		valhelsia_core-16.0.11.jar                        |Valhelsia Core                |valhelsia_core                |16.0.11             |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.6.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.6        |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.435-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		DragonSurvival_DragonEditor-1.16.5-0.13.42_nonpubl|Dragon Survival               |dragonsurvival                |version             |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.65.jar                  |GeckoLib                      |geckolib3                     |3.0.65              |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.5-1.6.3.jar                   |BetterEnd Forge               |betterendforge                |1.16.5-1.6.3        |DONE      |Manifest: NOSIGNATURE
		effortlessbuilding-1.16.3-2.22.jar                |Effortless Building           |effortlessbuilding            |1.16.3-2.22         |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b70bb032-b969-407b-a617-4983de041a67
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['blockEdragonn'/253, l='ServerLevel[New World4d57ctug]', x=252.50, y=65.00, z=113.50]]
	Data Packs: vanilla, mod:tenshilib (incompatible), mod:treechop, mod:mowziesmobs (incompatible), mod:swingthroughgrass (incompatible), mod:biomesoplenty, mod:jei, mod:abnormals_core, mod:medieval_craft, mod:upgrade_aquatic, mod:goblinsanddungeons, mod:whisperwoods, mod:guideapi-vp (incompatible), mod:patchouli (incompatible), mod:bettercaves (incompatible), mod:journeymap (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:autoreglib (incompatible), mod:yungsapi, mod:outer_end, mod:fantasy, mod:environmental, mod:dungeoncrawl, mod:betterstrongholds, mod:betteranimalsplus (incompatible), mod:badmobs (incompatible), mod:guardvillagers, mod:endergetic, mod:vampirism, mod:werewolves, mod:iceandfire (incompatible), mod:smallships, mod:forge, mod:quark (incompatible), mod:improvedmobs (incompatible), mod:cosmeticarmorreworked (incompatible), mod:valhelsia_core, mod:valhelsia_structures, mod:twilightforest, mod:dragonsurvival, mod:bettermineshafts, mod:geckolib3 (incompatible), mod:betterendforge, mod:effortlessbuilding (incompatible), mod:dsurround
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Drulikar** [comment]
The call stack for this report looks very similar to another issue. See my reply here: https://github.com/DragonSurvivalTeam/DragonSurvival/issues/131#issuecomment-1082702497
