### ISSUE TITLE
[1.18.2 Forge Bug]: Crashing after spawning a Dragon Knight

### ISSUE THREAD

**Issue by Reshy** [DragonSurvivalTeam/DragonSurvival#147]
### ■ Your Discord ID

Reshy#5860

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.0.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Forge crashed upon trying to force a dragon knight spawn using a spawn egg from creative mode.  Might be a conflict with a mod modifying mod like Champions/Infernal Mobs, however it's marked as a rendering exception.

### ■ To Reproduce

Using a spawn egg for a dragon knight after spawning a knight hound from creative mode.

### ■ Expected behavior

Game shouldn't crash after using a spawn egg.

### ■ Crash Report

[05:45:14] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1423) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1218) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1059) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:833) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119194_(net.minecraft.client.renderer.MultiBufferSource, java.util.function.Function)" because "$$13" is null
	at net.minecraft.client.renderer.blockentity.BannerRenderer.m_112074_(BannerRenderer.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer.m_108829_(BlockEntityWithoutLevelRenderer.java:156) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:159) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174242_(ItemRenderer.java:230) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174269_(ItemRenderer.java:224) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.creatures.KnightRenderer.renderRecursively(KnightRenderer.java:37) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23127!/:1.18.2-1.1.11]
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.renderRecursively(IGeoRenderer.java:59) ~[geckolib-1.18-forge-3.0.15.jar%23148!/:3.0.15]
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.creatures.KnightRenderer.renderRecursively(KnightRenderer.java:41) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23127!/:1.18.2-1.1.11]
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.renderRecursively(IGeoRenderer.java:59) ~[geckolib-1.18-forge-3.0.15.jar%23148!/:3.0.15]
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.creatures.KnightRenderer.renderRecursively(KnightRenderer.java:41) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23127!/:1.18.2-1.1.11]
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.renderRecursively(IGeoRenderer.java:59) ~[geckolib-1.18-forge-3.0.15.jar%23148!/:3.0.15]
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.creatures.KnightRenderer.renderRecursively(KnightRenderer.java:41) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23127!/:1.18.2-1.1.11]
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.renderRecursively(IGeoRenderer.java:59) ~[geckolib-1.18-forge-3.0.15.jar%23148!/:3.0.15]
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.creatures.KnightRenderer.renderRecursively(KnightRenderer.java:41) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23127!/:1.18.2-1.1.11]
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.renderRecursively(IGeoRenderer.java:59) ~[geckolib-1.18-forge-3.0.15.jar%23148!/:3.0.15]
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.creatures.KnightRenderer.renderRecursively(KnightRenderer.java:41) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23127!/:1.18.2-1.1.11]
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.render(IGeoRenderer.java:38) ~[geckolib-1.18-forge-3.0.15.jar%23148!/:3.0.15]
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:147) ~[geckolib-1.18-forge-3.0.15.jar%23148!/:3.0.15]
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.m_7392_(GeoEntityRenderer.java:42) ~[geckolib-1.18-forge-3.0.15.jar%23148!/:3.0.15]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:129) ~[client-1.18.2-20220404.173914-srg.jar%23267!/:?]
	... 20 more

**Comment by Reshy** [comment]
![2022-04-29_19 26 20](https://user-images.githubusercontent.com/2096384/166086927-0c1f9ac2-0661-44b3-86be-47e5c31d8d0b.png)
He spawns correctly now from the spawn egg.
