### ISSUE TITLE
[1.18.2 Forge Bug]: Crash on World Gen

### ISSUE THREAD

**Issue by Reshy** [DragonSurvivalTeam/DragonSurvival#148]
### ■ Your Discord ID

Reshy#5860

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.0.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Forge crashed attempting to generate world, Dragon Survival was noted to have thrown an exception.  Might be due to a recently installed mod, I'll be checking that next.

### ■ To Reproduce

Generate a world.

### ■ Expected behavior

World should load without issue.

### ■ Crash Report

[06:37:26] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.world.effect.MobEffectInstance.m_19544_()" because the return value of "com.mojang.datafixers.util.Pair.getFirst()" is null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonConfigHandler onConfigLoad(Lnet/minecraftforge/fml/event/config/ModConfigEvent$Loading;)V
		2: ASM: class by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler onConfigLoad(Lnet/minecraftforge/fml/event/config/ModConfigEvent$Loading;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.effect.MobEffectInstance.m_19544_()" because the return value of "com.mojang.datafixers.util.Pair.getFirst()" is null
	at TRANSFORMER/dragonsurvival@1.18.2-0.10.0/by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler.calculateDragonFoodProperties(DragonFoodHandler.java:200)
	at TRANSFORMER/dragonsurvival@1.18.2-0.10.0/by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler.buildDragonFoodMap(DragonFoodHandler.java:148)
	at TRANSFORMER/dragonsurvival@1.18.2-0.10.0/by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler.rebuildFoodMap(DragonFoodHandler.java:86)
	at TRANSFORMER/dragonsurvival@1.18.2-0.10.0/by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler.onConfigLoad(DragonFoodHandler.java:78)
	at net.minecraftforge.eventbus.ASMEventHandler_1121_DragonFoodHandler_onConfigLoad_Loading.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:41)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:135)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:135)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50)
	at TRANSFORMER/forge@40.1.0/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:81)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)

[06:37:26] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.effect.MobEffectInstance.m_19544_()" because the return value of "com.mojang.datafixers.util.Pair.getFirst()" is null
	at by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler.calculateDragonFoodProperties(DragonFoodHandler.java:200) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23130!/:1.18.2-1.1.11]
	at by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler.buildDragonFoodMap(DragonFoodHandler.java:148) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23130!/:1.18.2-1.1.11]
	at by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler.rebuildFoodMap(DragonFoodHandler.java:86) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23130!/:1.18.2-1.1.11]
	at by.dragonsurvivalteam.dragonsurvival.common.handlers.DragonFoodHandler.onConfigLoad(DragonFoodHandler.java:78) ~[DragonSurvival_DragonEditor-1.18.2-0.11.0.jar%23130!/:1.18.2-1.1.11]
	at net.minecraftforge.eventbus.ASMEventHandler_1121_DragonFoodHandler_onConfigLoad_Loading.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:41) ~[javafmllanguage-1.18.2-40.1.0.jar%23282!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:135) ~[fmlcore-1.18.2-40.1.0.jar%23281!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:135) ~[fmlcore-1.18.2-40.1.0.jar%23281!/:?]
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.18.2-40.1.0.jar%23281!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.18.2-40.1.0.jar%23281!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.1.0.jar%23281!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.1.0.jar%23281!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:81) ~[forge-1.18.2-40.1.0-universal.jar%23284!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63) ~[client-1.18.2-20220404.173914-srg.jar%23280!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%23280!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23280!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[06:37:26] [Server thread/FATAL]: Preparing crash report with UUID 780b545c-5be1-45aa-af86-b2a9df2bb172
[06:37:26] [Server thread/ERROR]: This crash report has been saved to: E:\Personal\Archive\Games\Twitch MC\Instances\1.18.2 Forge\crash-reports\crash-2022-04-21_06.37.26-server.txt
[06:37:26] [Server thread/INFO]: Stopping server
[06:37:26] [Server thread/INFO]: Saving players
[06:37:26] [Server thread/INFO]: Saving worlds
[06:37:26] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null
	at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:544) ~[client-1.18.2-20220404.173914-srg.jar%23280!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:611) ~[client-1.18.2-20220404.173914-srg.jar%23280!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:174) ~[client-1.18.2-20220404.173914-srg.jar%23280!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:717) ~[client-1.18.2-20220404.173914-srg.jar%23280!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23280!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by BlackAures1** [comment]
Send the full report, no need to copy it. Just drag it into the comments section from your folder on your computer and it will be downloaded in its entirety.
