### ISSUE TITLE
[1.16.5 Forge Bug]: Forbidden and Arcanus incompatible

### ISSUE THREAD

**Issue by Akrae42** [DragonSurvivalTeam/DragonSurvival#185]
### ■ Your Discord ID

Akrae#1181

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.6.jar.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

Conflict with Forbidden and Arcanus prevents respawn in 1.16.5. Bug does not persist in 1.18.2
If you die and click respawn, nothing happens. Generates java error in log.
Happens whether you are playing a dragon or a human.

### ■ To Reproduce

1. Die.
2. Click respawn.
3. Nothing happens.

### ■ Expected behavior

Being able to respawn.

### ■ Crash Report

[14:49:27] [Server thread/FATAL]: Error executing task on Server
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51]
	at com.stal111.forbidden_arcanus.event.PlayerCloneListener.onPlayerClone(PlayerCloneListener.java:21) ~[?:16.2.3]
	at net.minecraftforge.eventbus.ASMEventHandler_180_PlayerCloneListener_onPlayerClone_Clone.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3253/918644872.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:496) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_193104_a(ServerPlayerEntity.java:1109) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:434) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:1234) ~[?:?]
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30) ~[?:?]
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$6533/547355967.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5832/124619412.run(Unknown Source) [?:?]

**Comment by BlackAures1** [comment]
Sent full crash report file

**Comment by theTyrfing** [comment]
I am having very similar issue with that mod as well.
