### ISSUE TITLE
[1.16.5 Forge Bug]: Game simply crashes when going to select a dragon.

### ISSUE THREAD

**Issue by BlueYoshi68** [DragonSurvivalTeam/DragonSurvival#257]
### ■ Your Discord ID

†𝔬𝖓𝓎#4166

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Go to open an altar, hover over any of the 3 dragons, game turns off.

### ■ To Reproduce

Go to open an altar, hover over any of the 3 dragons, game turns off.

### ■ Expected behavior

I expect....that to not happen.

### ■ Crash Report

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/26/23 1:41 PM
Description: Rendering entity in world

java.lang.NoSuchFieldError: parser
	at by.dragonsurvivalteam.dragonsurvival.client.models.DragonModel.setMolangQueries(DragonModel.java:83) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:277) ~[?:3.0.104] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:79) ~[?:3.0.104] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:31) ~[?:3.0.104] {re:classloading,re:mixin}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:184) ~[?:3.0.104] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer.render(DragonRenderer.java:70) ~[?:1.16.5-0.10.4] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer.func_225623_a_(DragonRenderer.java:32) ~[?:1.16.5-0.10.4] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:AccessorEntityRendererManager,pl:mixin:APP:dragonsurvival.mixins.json:MixinEntityRenderManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.lambda$renderEntityInInventory$2(ClientDragonRender.java:493) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender$$Lambda$6449/813603842.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.renderEntityInInventory(ClientDragonRender.java:491) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.renderEntityInInventory(ClientDragonRender.java:442) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI.renderDragon(DragonAltarGUI.java:153) ~[?:1.16.5-0.10.4] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI.func_230430_a_(DragonAltarGUI.java:92) ~[?:1.16.5-0.10.4] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:377) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:370) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:MixinGameRenderer,pl:mixin:APP:dragonsurvival.mixins.json:MixinGameRendererZoom,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.33.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$465/1288815068.call(Unknown Source) [forge-1.16.5-36.2.33.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at by.dragonsurvivalteam.dragonsurvival.client.models.DragonModel.setMolangQueries(DragonModel.java:83) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:277) ~[?:3.0.104] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:79) ~[?:3.0.104] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:31) ~[?:3.0.104] {re:classloading,re:mixin}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:184) ~[?:3.0.104] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer.render(DragonRenderer.java:70) ~[?:1.16.5-0.10.4] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer.func_225623_a_(DragonRenderer.java:32) ~[?:1.16.5-0.10.4] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: dragonsurvival:dummy_dragon (null)
	Entity ID: 1078
	Entity Name: entity.dragonsurvival.dummy_dragon
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer@47800bd7
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:AccessorEntityRendererManager,pl:mixin:APP:dragonsurvival.mixins.json:MixinEntityRenderManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.lambda$renderEntityInInventory$2(ClientDragonRender.java:493) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender$$Lambda$6449/813603842.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.renderEntityInInventory(ClientDragonRender.java:491) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.renderEntityInInventory(ClientDragonRender.java:442) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI.renderDragon(DragonAltarGUI.java:153) ~[?:1.16.5-0.10.4] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI.func_230430_a_(DragonAltarGUI.java:92) ~[?:1.16.5-0.10.4] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:377) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:370) ~[?:?] {re:classloading}

-- Screen render details --
Details:
	Screen name: by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI
	Mouse location: Scaled: (222, 107). Absolute: (444.000000, 215.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Anatoli01'/391, l='ClientLevel', x=185.50, y=64.00, z=-256.50]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,63,-256), Chunk: (at 0,3,0 in 11,-16; contains blocks 176,0,-256 to 191,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 164 game time, 164 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dragonsurvival.mixins.json:MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.33.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$465/1288815068.call(Unknown Source) [forge-1.16.5-36.2.33.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5691657056 bytes (5427 MB) / 6811549696 bytes (6496 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.33.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.33.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.33.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.33.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.33.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.33
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.33-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.33-universal.jar                |Forge                         |forge                         |36.2.33             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		DragonSurvival_DragonEditor-1.16.5-0.10.7.jar     |Dragon Survival               |dragonsurvival                |version             |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.104.jar                 |GeckoLib                      |geckolib3                     |3.0.104             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: dd2a3e32-a266-4694-9d16-59f6ade312ed
	Launched Version: 1.16.5-forge-36.2.33
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 526.86, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, RAD2-RP-1.16.5, rpggods-greek-resources-16.5.1.zip, quark:emote_resources (incompatible), packmenu (incompatible)
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor

**Comment by BlackAures1** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update#--1165
