### ISSUE TITLE
[1.18.2 Forge Bug]: Game crash with origin installed

### ISSUE THREAD

**Issue by Tr3c345** [DragonSurvivalTeam/DragonSurvival#280]
### ■ Your Discord ID

Tr3c3#5375

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.42
origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar
geckolib-forge-1.18-3.0.57
caelus-forge-1.18.1-3.0.0.2

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

So I was trying to play with origins mod but, when I put an origin that is damaged by water or has immunity to fire the game crashes.

### ■ To Reproduce

1) Play with origins mod and Dragon Survival
2) Create a new world
3) Select an origin with fire immunity or water breathing.
4)Crash

### ■ Expected behavior

I hope to be able to use the origin mod and the dragon survival individually but in the same world

### ■ Crash Report

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 28/4/23 19:22
Description: Ticking player

java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.mixin.EntityAccessor (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @7be2f29a; io.github.apace100.apoli.mixin.EntityAccessor is in module apoli@1.18.2-2.3.4.0 of loader 'TRANSFORMER' @7be2f29a)
	at io.github.edwinmindcraft.apoli.common.registry.condition.ApoliEntityConditions.lambda$static$1(ApoliEntityConditions.java:59) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:37) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:13) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$check$10(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:280) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?] {}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$orCodec$9(ConditionStreamConfiguration.java:37) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.check(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:15) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:8) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.lambda$isActive$6(PowerFactory.java:196) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:mixin,re:classloading}
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?] {}
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?] {}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.isActive(PowerFactory.java:196) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.isActive(ConfiguredPower.java:86) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.power.DamageOverTimePower.tick(DamageOverTimePower.java:36) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:160) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:165) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.component.PowerContainer.serverTick(PowerContainer.java:191) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.2.0-universal.jar%2362!/:?] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.livingTick(ApoliEventHandler.java:114) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_169_ApoliEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:324) ~[forge-1.18.2-40.2.0-universal.jar%2362!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:dragonsurvival.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:MixinPlayerEntity,pl:mixin:APP:origins.mixins.json:NoCobwebSlowdownMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$UpdateAir,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.edwinmindcraft.apoli.common.registry.condition.ApoliEntityConditions.lambda$static$1(ApoliEntityConditions.java:59) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:37) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:13) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$check$10(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:280) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?] {}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$orCodec$9(ConditionStreamConfiguration.java:37) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.check(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:15) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:8) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.lambda$isActive$6(PowerFactory.java:196) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:mixin,re:classloading}
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?] {}
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?] {}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.isActive(PowerFactory.java:196) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.isActive(ConfiguredPower.java:86) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.power.DamageOverTimePower.tick(DamageOverTimePower.java:36) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:160) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:165) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.component.PowerContainer.serverTick(PowerContainer.java:191) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.2.0-universal.jar%2362!/:?] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.livingTick(ApoliEventHandler.java:114) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%2356%2367!/:1.18.2-2.3.4.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_169_ApoliEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:324) ~[forge-1.18.2-40.2.0-universal.jar%2362!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:dragonsurvival.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:MixinPlayerEntity,pl:mixin:APP:origins.mixins.json:NoCobwebSlowdownMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$UpdateAir,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 13
	Entity Name: Tr3c3_OwO
	Entity's Exact location: 3.21, -60.00, -4.74
	Entity's Block location: World: (3,-60,-5), Section: (at 3,4,11 in 0,-4,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3453235704 bytes (3293 MiB) / 4596957184 bytes (4384 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 750 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1380
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3168
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 1.87
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 28083.80
	Virtual memory used (MB): 21017.32
	Swap memory total (MB): 3584.00
	Swap memory used (MB): 320.39
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Tr3c3_OwO'/13, l='ServerLevel[Mundo nuevo]', x=3.21, y=-60.00, z=-4.74]]
	Data Packs: vanilla, mod:calio (incompatible), mod:caelus (incompatible), mod:forge, mod:apoli (incompatible), mod:origins (incompatible), mod:dragonsurvival (incompatible), mod:additionalentityattributes, mod:geckolib3 (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		calio-forge-1.18.2-1.18.2-1.6.0.0.jar             |Calio                         |calio                         |1.18.2-1.6.0.0      |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		apoli-forge-1.18.2-1.18.2-2.3.4.0.jar             |Apoli                         |apoli                         |1.18.2-2.3.4.0      |DONE      |Manifest: NOSIGNATURE
		origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar    |Origins                       |origins                       |1.18.2-1.5.0.1      |DONE      |Manifest: NOSIGNATURE
		DragonSurvival-1.18.2-1.5.42.jar                  |Dragon Survival               |dragonsurvival                |1.18.2-1.5.42       |DONE      |Manifest: NOSIGNATURE
		Forge-1.0.1-1.18.2.jar                            |Additional Entity Attributes  |additionalentityattributes    |1.0.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 4d5b58a6-0144-4481-a5b8-5cabc1bb5349
	FML: 40.2
	Forge: net.minecraftforge:40.2.0

**Comment by FirDragon** [comment]
This seems to be a problem with Apoli, have you tried creating a new world with Dragon Survival disabled and doing the steps above?
