### ISSUE TITLE
[1.16.5 Forge Bug]: 

### ISSUE THREAD

**Issue by Doibi** [DragonSurvivalTeam/DragonSurvival#365]
### ■ Your Discord ID

Reddogg82

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7.jar

The game just straight up breaks whenever the Dragon editor appears either using the command or dragon altar

I also tested it in an empty modlist

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Game just freezes and crashes

### ■ To Reproduce

1. place altar
2. right click
3. crash

### ■ Expected behavior

open the dragon selection

### ■ Crash Report

[crash-2023-08-29_23.03.55-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12471291/crash-2023-08-29_23.03.55-client.txt)

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/29/23 11:03 PM
Description: Rendering entity in world

java.lang.NoSuchFieldError: parser
	at by.dragonsurvivalteam.dragonsurvival.client.models.DragonModel.setMolangQueries(DragonModel.java:83) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:277) ~[?:3.0.106] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:84) ~[?:3.0.106] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setCustomAnimations(AnimatedGeoModel.java:50) ~[?:3.0.106] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setCustomAnimations(AnimatedGeoModel.java:31) ~[?:3.0.106] {re:classloading,re:mixin}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:184) ~[?:3.0.106] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer.render(DragonRenderer.java:70) ~[?:1.16.5-0.10.4] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer.func_225623_a_(DragonRenderer.java:32) ~[?:1.16.5-0.10.4] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:AccessorEntityRendererManager,pl:mixin:APP:dragonsurvival.mixins.json:MixinEntityRenderManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.lambda$renderEntityInInventory$2(ClientDragonRender.java:493) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender$$Lambda$6527/2056109041.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.renderEntityInInventory(ClientDragonRender.java:491) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.renderEntityInInventory(ClientDragonRender.java:442) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI.renderDragon(DragonAltarGUI.java:153) ~[?:1.16.5-0.10.4] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI.func_230430_a_(DragonAltarGUI.java:92) ~[?:1.16.5-0.10.4] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:377) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:370) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:MixinGameRenderer,pl:mixin:APP:dragonsurvival.mixins.json:MixinGameRendererZoom,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/1456265041.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at by.dragonsurvivalteam.dragonsurvival.client.models.DragonModel.setMolangQueries(DragonModel.java:83) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:277) ~[?:3.0.106] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:84) ~[?:3.0.106] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setCustomAnimations(AnimatedGeoModel.java:50) ~[?:3.0.106] {re:classloading,re:mixin}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setCustomAnimations(AnimatedGeoModel.java:31) ~[?:3.0.106] {re:classloading,re:mixin}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:184) ~[?:3.0.106] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer.render(DragonRenderer.java:70) ~[?:1.16.5-0.10.4] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer.func_225623_a_(DragonRenderer.java:32) ~[?:1.16.5-0.10.4] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: dragonsurvival:dummy_dragon (null)
	Entity ID: 658
	Entity Name: entity.dragonsurvival.dummy_dragon
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: by.dragonsurvivalteam.dragonsurvival.client.render.entity.dragon.DragonRenderer@7a8d6eb3
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonsurvival.mixins.json:AccessorEntityRendererManager,pl:mixin:APP:dragonsurvival.mixins.json:MixinEntityRenderManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.lambda$renderEntityInInventory$2(ClientDragonRender.java:493) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender$$Lambda$6527/2056109041.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.renderEntityInInventory(ClientDragonRender.java:491) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.render.ClientDragonRender.renderEntityInInventory(ClientDragonRender.java:442) ~[?:1.16.5-0.10.4] {re:classloading,re:mixin}
	at by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI.renderDragon(DragonAltarGUI.java:153) ~[?:1.16.5-0.10.4] {re:classloading}
	at by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI.func_230430_a_(DragonAltarGUI.java:92) ~[?:1.16.5-0.10.4] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:377) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:370) ~[?:?] {re:classloading}

-- Screen render details --
Details:
	Screen name: by.dragonsurvivalteam.dragonsurvival.client.gui.DragonAltarGUI
	Mouse location: Scaled: (237, 127). Absolute: (948.000000, 507.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['doibi101'/214, l='ClientLevel', x=-157.43, y=64.00, z=-208.44]]
	Chunk stats: Client Chunk Cache: 841, 575
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,63,-208), Chunk: (at 0,3,0 in -9,-13; contains blocks -144,0,-208 to -129,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 595 game time, 595 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dragonsurvival.mixins.json:MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/1456265041.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 536970952 bytes (512 MB) / 2168979456 bytes (2068 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		DragonSurvival_DragonEditor-1.16.5-0.10.7.jar     |Dragon Survival               |dragonsurvival                |version             |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 90225844-ab7d-4ce6-9536-2215ccbc13ca
	Launched Version: forge-36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.23, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz

**Comment by BlackAures1** [comment]
You need Geckolib 3.0.93 https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update
