### ISSUE TITLE
[Compatibility]: Dragon Survival always crashes when transforming into a dragon, no matter the methods of transformation

### ISSUE THREAD

**Issue by flinbers** [DragonSurvivalTeam/DragonSurvival#418]
### ■ Your Discord ID

andiael

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.01.2024

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Description of incompatibility

When transforming via commands or dragon altar, the game freezes then crashes.

### ■ To Reproduce

By transforming into any dragon

### ■ Crash Report

---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-01-24 21:41:12
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1431) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1229) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:apoli.mixins.json:GameRendererMixin from mod apoli,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin from mod ad_astra,pl:mixin:APP:embeddiumplus.mixin.json:darkness.MixinGameRenderer from mod embeddiumplus,pl:mixin:APP:immersive_aircraft.mixins.json:GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer from mod railways,pl:mixin:APP:mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes,pl:mixin:APP:dragonsurvival.mixins.json:AccessorGameRenderer from mod dragonsurvival,pl:mixin:APP:dragonsurvival.mixins.json:MixinGameRenderer from mod dragonsurvival,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:apoli.mixins.json:GameRendererMixin from mod apoli,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin from mod ad_astra,pl:mixin:APP:embeddiumplus.mixin.json:darkness.MixinGameRenderer from mod embeddiumplus,pl:mixin:APP:immersive_aircraft.mixins.json:GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer from mod railways,pl:mixin:APP:mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes,pl:mixin:APP:dragonsurvival.mixins.json:AccessorGameRenderer from mod dragonsurvival,pl:mixin:APP:dragonsurvival.mixins.json:MixinGameRenderer from mod dragonsurvival,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.20.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1431) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1229) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:apoli.mixins.json:GameRendererMixin from mod apoli,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin from mod ad_astra,pl:mixin:APP:embeddiumplus.mixin.json:darkness.MixinGameRenderer from mod embeddiumplus,pl:mixin:APP:immersive_aircraft.mixins.json:GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer from mod railways,pl:mixin:APP:mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes,pl:mixin:APP:dragonsurvival.mixins.json:AccessorGameRenderer from mod dragonsurvival,pl:mixin:APP:dragonsurvival.mixins.json:MixinGameRenderer from mod dragonsurvival,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Flinbers'/264, l='ClientLevel', x=801.62, y=66.00, z=588.44]]
	Chunk stats: 1024, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (944,66,-524), Section: (at 0,2,4 in 59,4,-33; chunk contains blocks 944,-64,-528 to 959,319,-513), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,-64,-1024 to 1023,319,-513)
	Level time: 3019930 game time, 527413 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin from mod citadel,pl:mixin:APP:mixins.cardinal_components_entity.json:client.MixinClientWorld from mod cardinal_components_entity,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin from mod supplementaries,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.ClientWorldMixin from mod embeddium,pl:mixin:APP:the_bumblezone-common.mixins.json:client.ClientLevelAccessor from mod the_bumblezone,pl:mixin:APP:the_bumblezone-common.mixins.json:client.ClientLevelMixin from mod the_bumblezone,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin from mod pehkui,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin from mod flywheel,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.ClientLevelMixin from mod embeddiumplus,pl:mixin:APP:bclib.mixins.client.json:ClientLevelMixin from mod bclib,pl:mixin:APP:architectury.mixins.json:MixinClientLevel from mod architectury,pl:mixin:APP:dragonsurvival.mixins.json:MixinClientWorld from mod dragonsurvival,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:ClientWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin from mod blueprint,pl:mixin:APP:alexscaves.mixins.json:client.ClientLevelMixin from mod alexscaves,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23578!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.20.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: pointblank_resources, builtin/towntalk, create:legacy_copper, mod_resources, vanilla, Moonlight Mods Dynamic Assets, create:destroy_create_patches

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 808527656 bytes (771 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6600M
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: DriverVersion=31.0.22011.4008
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37285.79
	Virtual memory used (MB): 25803.78
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 147.03
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.2.20
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 6600M GL version 4.6.0 Core Profile Context 23.9.3.230915, ATI Technologies Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: pointblank_resources, builtin/towntalk (incompatible), create:legacy_copper, mod_resources, vanilla, Moonlight Mods Dynamic Assets, create:destroy_create_patches
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	Sinytra Connector: 1.0.0-beta.32+1.20.1
		SINYTRA CONNECTOR IS PRESENT!
		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker.
		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues.
		Installed Fabric mods:
		| ================================================== | ============================== | ============================== | ==================== |
		| runes-fabric-0.9.11+1.20.1_mapped_srg_1.20.1.jar   | Runes                          | runes                          | 0.9.111.20.1         |
		| trinkets-3.7.1_mapped_srg_1.20.1.jar               | Trinkets                       | trinkets                       | 3.7.1                |
		| trinkets-3.7.1$cardinal-components-entity-5.2.0_ma | Cardinal Components API (entit | cardinal_components_entity     | 5.2.0                |
		| simplyskills-1.0.0+1.20.1_mapped_srg_1.20.1.jar    | SimplySkills                   | simplyskills                   | 1.0.01.20.1          |
		| spell_engine-0.12.5+1.20.1_mapped_srg_1.20.1.jar   | Spell Engine                   | spell_engine                   | 0.12.51.20.1         |
		| autotag-2.0.2+1.20_mapped_srg_1.20.1.jar           | AutoTag Convention             | autotag_convention             | 2.0.21.20            |
		| paladins-1.0.5+1.20.1_mapped_srg_1.20.1.jar        | Paladins & Priests (RPG Series | paladins                       | 1.0.51.20.1          |
		| autotag-2.0.2+1.20$autotag-api-2.0.2+1.20_mapped_s | AutoTag                        | autotag                        | 2.0.21.20            |
		| better-end-4.0.11_mapped_srg_1.20.1.jar            | Better End                     | betterend                      | 4.0.11               |
		| paladins-1.0.5+1.20.1$mixinextras-fabric-0.2.0_map | MixinExtras                    | com_github_llamalad7_mixinextr | 0.2.0                |
		| bclib-3.0.14$wunderlib-1.1.5_mapped_srg_1.20.1.jar | WunderLib                      | wunderlib                      | 1.1.5                |
		| bclib-3.0.14_mapped_srg_1.20.1.jar                 | BCLib                          | bclib                          | 3.0.14               |
		| spell_power-fabric-0.9.19+1.20.1_mapped_srg_1.20.1 | Spell Power Attribute          | spell_power                    | 0.9.191.20.1         |
		| trinkets-3.7.1$cardinal-components-base-5.2.0_mapp | Cardinal Components API (base) | cardinal_components_base       | 5.2.0                |
		| paladins-1.0.5+1.20.1$TinyConfig-2.3.2_mapped_srg_ | TinyConfig                     | com_github_zsoltmolnarrr_tinyc | 2.3.2                |
		| azurelibarmor-fabric-1.20.1-2.0.3_mapped_srg_1.20. | AzureLib Armor                 | azurelibarmor                  | 2.0.3                |
		| paladins-1.0.5+1.20.1$structure-pool-api-1.0+1.20. | Structure Pool API             | structure_pool_api             | 1.01.20.1            |
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.10.0
		lowcodefml@null

**Comment by SiverDX** [comment]
crash log seems cut off, it should contain a list of your mods

are you using mana and artifice?

**Comment by flinbers** [comment]
> crash log seems cut off, it should contain a list of your mods
> 
> are you using mana and artifice?

Sorry about that, couldn't paste all the list. And yes, i am using mana and artifice

**Comment by SiverDX** [comment]
they released a new version which might help with this problem
so far it had issues when mods cancelled render events due to its way of handling the pose stack

**Comment by flinbers** [comment]
trying a lot of things for the past hour. tested ds with mna and it worked fine (the new version that you talked about), but when put together in the modpack everything goes wrong. should i send the new crash report?

**Comment by flinbers** [comment]
dude, tysm, solved it with the help of a friend;
