### ISSUE TITLE
---- Minecraft Crash Report ----1

### ISSUE THREAD

**Issue by BlackAures1** [DragonSurvivalTeam/DragonSurvival#5]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 4/17/21 3:13 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at software.bernie.geckolib3.core.controller.AnimationController.process(AnimationController.java:432) ~[?:3.0.15] {re:classloading}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.tickAnimation(AnimationProcessor.java:65) ~[?:3.0.15] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:76) ~[?:3.0.15] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:32) ~[?:3.0.15] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:136) ~[?:3.0.15] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.func_225623_a_(GeoEntityRenderer.java:41) ~[?:3.0.15] {re:classloading}
	at by.jackraidenph.dragonsurvival.handlers.ClientEvents.lambda$thirdPersonPreRender$3(ClientEvents.java:249) ~[?:0.0.25] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at by.jackraidenph.dragonsurvival.handlers.ClientEvents.thirdPersonPreRender(ClientEvents.java:205) ~[?:0.0.25] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_38_ClientEvents_thirdPersonPreRender_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:61) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:39) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:305) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at by.jackraidenph.dragonsurvival.gui.DragonScreen.drawEntityOnScreen(DragonScreen.java:102) ~[?:0.0.25] {re:classloading}
	at by.jackraidenph.dragonsurvival.gui.DragonScreen.func_146976_a(DragonScreen.java:70) ~[?:0.0.25] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:73) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.render(DisplayEffectsScreen.java:45) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at by.jackraidenph.dragonsurvival.gui.DragonScreen.render(DragonScreen.java:157) ~[?:0.0.25] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:736) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:804) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[ForgeOptiFine%201.15.2.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.49.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.geckolib3.core.controller.AnimationController.process(AnimationController.java:432)
	at software.bernie.geckolib3.core.processor.AnimationProcessor.tickAnimation(AnimationProcessor.java:65)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:76)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:32)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:136)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.func_225623_a_(GeoEntityRenderer.java:41)
	at by.jackraidenph.dragonsurvival.handlers.ClientEvents.lambda$thirdPersonPreRender$3(ClientEvents.java:249)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at by.jackraidenph.dragonsurvival.handlers.ClientEvents.thirdPersonPreRender(ClientEvents.java:205)
	at net.minecraftforge.eventbus.ASMEventHandler_38_ClientEvents_thirdPersonPreRender_Pre.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:61)
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:39)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 2234
	Entity Name: Veoros
	Entity's Exact location: 444.18, 12.00, 112.01
	Entity's Block location: World: (444,12,112), Chunk: (at 12,0,0 in 27,7; contains blocks 432,0,112 to 447,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.PlayerRenderer@5a654e05
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:305)
	at by.jackraidenph.dragonsurvival.gui.DragonScreen.drawEntityOnScreen(DragonScreen.java:102)
	at by.jackraidenph.dragonsurvival.gui.DragonScreen.func_146976_a(DragonScreen.java:70)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:73)
	at net.minecraft.client.gui.DisplayEffectsScreen.render(DisplayEffectsScreen.java:45)
	at by.jackraidenph.dragonsurvival.gui.DragonScreen.render(DragonScreen.java:157)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:736)

-- Screen render details --
Details:
	Screen name: by.jackraidenph.dragonsurvival.gui.DragonScreen
	Mouse location: Scaled: (320, 169). Absolute: (960.000000, 508.000000)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['Veoros'/2234, l='MpServer', x=444.18, y=12.00, z=112.01], RemoteClientPlayerEntity['BlackAures'/1253, l='MpServer', x=457.70, y=65.00, z=138.36]]
	Chunk stats: Client Chunk Cache: 729, 494
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 934184822763882444
	Level generator: ID 03 - amplified, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (256,77,-224), Chunk: (at 0,4,0 in 16,-14; contains blocks 256,0,-224 to 271,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 5115899 game time, 1241114 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8992535320 bytes (8575 MB) / 10435428352 bytes (9952 MB) up to 10435428352 bytes (9952 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx9935M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.49.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.49.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.49.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.49.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.15.2_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.49.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.49
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.49-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.49-universal.jar Forge {forge@31.2.49 DONE}
		DragonSurvival-0.0.25.jar Dragon Survival {dragonsurvival@0.0.23 DONE}
		geckolib-forge-1.15.2-3.0.15.jar GeckoLib Example Mod {geckolib3@3.0.15 DONE}
	Launched Version: ForgeOptiFine 1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.92, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	CPU: 4x Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G6
	OptiFine Build: 20210124-205244
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.92
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by AlexiyOrlov** [comment]
Fixed
