### ISSUE TITLE
[1.19.2 Bug]: Game completely closes when trying to open the Dragon Inventory.

### ISSUE THREAD

**Issue by axol0lt** [DragonSurvivalTeam/DragonSurvival#518]
### ■ Your Discord ID or other contacts

_axol0tl

### ■ Dragon Survival version

DragonSurvival-1.19.2-09.06.2024

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

I have quite a few mods, but as soon as I open the dragon inventory, it freezes and crashes the game entirely. One suspicion I've had in the latest.log file says, "[Sound engine/ERROR] [com.mojang.blaze3d.audio.OpenAlUtil/]: Stop: Invalid parameter parameter value", which has been known to crash the game. One way you could replicate this is maybe playing a custom disc from a mod called Etched with Sound Physics Remastered enabled, and then opening the dragon inventory? One thing I did do though is mess with the Max Health for dragon growth server settings.

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/15825620/latest.log)

**Comment by Psither** [comment]
That... is a _lot_ of errors.

None of these even seem related to DragonSurvival; the system is already extremely unstable and just opening the inventory is enough to crash.

**Comment by Psither** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/97207971/05e781ac-8661-42ea-891a-0a7cd65ba174)

**Comment by SiverDX** [comment]
the first batch is from the essential launcher (?), usually unrelated to the actual problem
server started timing out after a problem from https://www.curseforge.com/minecraft/mc-mods/waystones-teleport-pets

(first error at 10:22:36, time out of 32 seconds logged at 10:23:10)

```
[13Jun2024 10:22:36.937] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: 'net.minecraft.world.entity.LivingEntity net.minecraft.world.entity.TamableAnimal.m_269323_()'
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: fr.shohqapik.w2pets.W2PetsMod@688b4981 onWaystoneTeleport(Lnet/blay09/mods/waystones/api/WaystoneTeleportEvent$Pre;)V
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.LivingEntity net.minecraft.world.entity.TamableAnimal.m_269323_()'
	at TRANSFORMER/w2pets@1.0/fr.shohqapik.w2pets.W2PetsMod.onWaystoneTeleport(W2PetsMod.java:30)
	at TRANSFORMER/w2pets@1.0/fr.shohqapik.w2pets.__W2PetsMod_onWaystoneTeleport_Pre.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/balm@4.6.0/net.blay09.mods.balm.forge.event.ForgeBalmEvents.fireEvent(ForgeBalmEvents.java:81)
	at TRANSFORMER/waystones@11.4.2/net.blay09.mods.waystones.core.PlayerWaystoneManager.tryTeleport(PlayerWaystoneManager.java:221)
	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.datafixers.util.Either.flatMap(Either.java:191)
	at TRANSFORMER/waystones@11.4.2/net.blay09.mods.waystones.core.PlayerWaystoneManager.tryTeleportToWaystone(PlayerWaystoneManager.java:210)
	at TRANSFORMER/waystones@11.4.2/net.blay09.mods.waystones.network.message.SelectWaystoneMessage.handle(SelectWaystoneMessage.java:36)
	at TRANSFORMER/balm@4.6.0/net.blay09.mods.balm.forge.network.ForgeBalmNetworking.lambda$registerServerboundPacket$6(ForgeBalmNetworking.java:180)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Unknown Source)
```
