### ISSUE TITLE
[1.20.1 Bug]: Spamming "Async chunk entity get" when arclight is used

### ISSUE THREAD

**Issue by BillZhucn** [DragonSurvivalTeam/DragonSurvival#523]
### ■ Your Discord ID or other contacts

bill_owo

### ■ Dragon Survival version

dragonsurvival-1.20.1-13.06.2024-all.jar

### ■ Forge/Neoforge version

forge 47.2.20

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

When using arclight, the error occured when any dragon moves.

### ■ Crash Report File and Logs

```
[15Jun2024 11:32:08.613] [Netty Server IO #2/DEBUG] [Implementer/ASYNC_CATCHER]: Async chunk entity get
java.lang.IllegalStateException: Asynchronous chunk entity get!
	at io.izzel.arclight.boot.asm.AsyncCatcher.checkOp(AsyncCatcher.java:236) ~[arclight-forge-1.20.1-1.0.6-SNAPSHOT.jar%2383!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {}
	at net.minecraft.server.level.ServerLevel.m_142646_(ServerLevelMixin.java) ~[server-1.20.1-20230612.114412-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.minecraft.server.level.ServerLevel.m_6815_(ServerLevelMixin.java:1104) ~[server-1.20.1-20230612.114412-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at by.dragonsurvivalteam.dragonsurvival.network.player.PacketSyncCapabilityMovement.handle(PacketSyncCapabilityMovement.java:58) ~[%5B龙之生存%5D%20dragonsurvival-1.20.1-13.06.2024-all.jar%23231!/:1.20.1-13.06.2024] {re:classloading,pl:rei_plugin_compatibilities:B}
	at by.dragonsurvivalteam.dragonsurvival.network.player.PacketSyncCapabilityMovement.handle(PacketSyncCapabilityMovement.java:17) ~[%5B龙之生存%5D%20dragonsurvival-1.20.1-13.06.2024-all.jar%23231!/:1.20.1-13.06.2024] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.20.1-47.2.20-universal.jar%23258!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.20.1-47.2.20-universal.jar%23258!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.20.1-47.2.20-universal.jar%23258!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:63) ~[forge-1.20.1-47.2.20-universal.jar%23258!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.20.1-47.2.20-universal.jar%23258!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooksMixin.java:80) ~[forge-1.20.1-47.2.20-universal.jar%23258!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.arclight.forge.json:NetworkHooksMixin,pl:mixin:A}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooksMixin.java:80) ~[forge-1.20.1-47.2.20-universal.jar%23258!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.arclight.forge.json:NetworkHooksMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerPlayNetHandlerMixin.java:1677) ~[server-1.20.1-20230612.114412-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.20.1-20230612.114412-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.network.Connection.m_129517_(ConnectionMixin.java:174) ~[server-1.20.1-20230612.114412-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.arclight.core.json:network.ConnectionMixin,pl:mixin:A}
	at net.minecraft.network.Connection.channelRead0(ConnectionMixin.java:159) ~[server-1.20.1-20230612.114412-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.arclight.core.json:network.ConnectionMixin,pl:mixin:A}
	at net.minecraft.network.Connection.channelRead0(ConnectionMixin.java:50) ~[server-1.20.1-20230612.114412-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.arclight.core.json:network.ConnectionMixin,pl:mixin:A}
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar%23117!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
```

**Comment by seelderr** [comment]
PacketSyncCapabilityMovement won't exist in the same form in 1.21 onwards. Going to close this as WNF.
