### ISSUE TITLE
[1.18.2 Bug]: latest version labels broken in the editor

### ISSUE THREAD

**Issue by shadow4378a** [DragonSurvivalTeam/DragonSurvival#670]
### ■ Dragon Survival version

DragonSurvival-1.18.2-27.07.2024

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

very simple all the labels in the editor are broken, instead of showing their names its showing their id's like off the top of my head "cavedragonback1" for example, probably not an actual id i saw this yesterday and forgot to to make a report so i dont remember the id's it displayed, i am unsure if it was just a problem with the modpack i was using or if it was a problem with the mod, as i attempted to create a second modpack with just dragon survival and it crashed instantly, i tried multiple forge versions but it crashes instantly unsure whats going on. i have attached the crash log from the modpack i attempted to use for testing

### ■ Crash Report File and Logs

[04:16:59] [main/INFO]: ModLauncher running: args [--username, Shadow4378a, --version, forge-40.2.21, --gameDir, C:\Users\minec\curseforge\minecraft\Instances\gbffgfbhb, --assetsDir, C:\Users\minec\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, adf36d7b9e904a978c603903e312109e, --accessToken, ????????, --clientId, YmRlODJjY2UtYTQ5Yi00ZGQyLWFmNzEtZDA2YTc2YTJkYTFm, --xuid, 2535414132494152, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.21, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[04:16:59] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[04:16:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/minec/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[04:16:59] [main/INFO]: Found mod file DragonSurvival-1.18.2-27.07.2024.jar of type MOD with provider {mods folder locator at C:\Users\minec\curseforge\minecraft\Instances\gbffgfbhb\mods}
[04:16:59] [main/WARN]: Mod file C:\Users\minec\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.21\fmlcore-1.18.2-40.2.21.jar is missing mods.toml file
[04:17:00] [main/WARN]: Mod file C:\Users\minec\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.21\javafmllanguage-1.18.2-40.2.21.jar is missing mods.toml file
[04:17:00] [main/WARN]: Mod file C:\Users\minec\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.21\lowcodelanguage-1.18.2-40.2.21.jar is missing mods.toml file
[04:17:00] [main/WARN]: Mod file C:\Users\minec\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.21\mclanguage-1.18.2-40.2.21.jar is missing mods.toml file
[04:17:00] [main/INFO]: Found mod file fmlcore-1.18.2-40.2.21.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@669d2b1b
[04:17:00] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.2.21.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@669d2b1b
[04:17:00] [main/INFO]: Found mod file lowcodelanguage-1.18.2-40.2.21.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@669d2b1b
[04:17:00] [main/INFO]: Found mod file mclanguage-1.18.2-40.2.21.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@669d2b1b
[04:17:00] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@669d2b1b
[04:17:00] [main/INFO]: Found mod file forge-1.18.2-40.2.21-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@669d2b1b
[04:17:00] [main/INFO]: No dependencies to load found. Skipping!
[04:17:00] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'geckolib3', Requested by: 'dragonsurvival', Expected range: '[3.0.47,)', Actual version: '[MISSING]'
[04:17:02] [main/INFO]: Compatibility level set to JAVA_17
[04:17:02] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-40.2.21, --gameDir, C:\Users\minec\curseforge\minecraft\Instances\gbffgfbhb, --assetsDir, C:\Users\minec\curseforge\minecraft\Install\assets, --uuid, adf36d7b9e904a978c603903e312109e, --username, Shadow4378a, --assetIndex, 1.18, --accessToken, ????????, --clientId, YmRlODJjY2UtYTQ5Yi00ZGQyLWFmNzEtZDA2YTc2YTJkYTFm, --xuid, 2535414132494152, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[04:17:19] [Render thread/WARN]: Assets URL 'union:/C:/Users/minec/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2355!/assets/.mcassetsroot' uses unexpected schema
[04:17:19] [Render thread/WARN]: Assets URL 'union:/C:/Users/minec/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2355!/data/.mcassetsroot' uses unexpected schema
[04:17:19] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:17:21] [Render thread/INFO]: Setting user: Shadow4378a
[04:17:22] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[04:17:30] [Render thread/FATAL]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod  edragonsurvival r requires  6geckolib3 r  o3.0.47 or above r
 7Currently,  6geckolib3 r 7 is  o nnot installed
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.18.2-40.2.21.jar%2356!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:95) ~[fmlcore-1.18.2-40.2.21.jar%2356!/:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:127) ~[fmlcore-1.18.2-40.2.21.jar%2356!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92) ~[forge-1.18.2-40.2.21-universal.jar%2360!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.2.21-universal.jar%2360!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92) ~[forge-1.18.2-40.2.21-universal.jar%2360!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:459) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.21.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[04:17:32] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[04:17:33] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[04:17:33] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[04:17:34] [Render thread/WARN]: Error loading class: software/bernie/geckolib3/model/AnimatedGeoModel (java.lang.ClassNotFoundException: software.bernie.geckolib3.model.AnimatedGeoModel)
[04:17:34] [Render thread/WARN]: Error loading class: software/bernie/geckolib3/core/processor/AnimationProcessor (java.lang.ClassNotFoundException: software.bernie.geckolib3.core.processor.AnimationProcessor)

**Comment by SiverDX** [comment]
>  Mod ID: 'geckolib3', Requested by: 'dragonsurvival', Expected range: '[3.0.47,)', Actual version: '[MISSING]'

you did not install geckolib

regarding the labels - the parts are only translated in 1.20 and 1.21 iirc

**Comment by shadow4378a** [comment]
> > Mod ID: 'geckolib3', Requested by: 'dragonsurvival', Expected range: '[3.0.47,)', Actual version: '[MISSING]'
> 
> you did not install geckolib
> 
> regarding the labels - the parts are only translated in 1.20 and 1.21 iirc

that explains the crash, im used to curseforge auto installing dependancies and for some reason it just didnt do that this time

**Comment by BlackAures1** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update#--1182
